version: "3.8"

networks:
  traefik:
    driver: overlay
    attachable: true

services:
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--api.insecure=true" # Enable dashboard for debugging
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=devex_traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8081" # Add a new entrypoint for the dashboard
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=parthkapoor.coder@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  core_service:
    image: ghcr.io/parthkapoor-dev/devex/core-service:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`api.devx.parthkapoor.me`)"
      - "traefik.http.routers.core.entrypoints=websecure"
      - "traefik.http.routers.core.tls.certresolver=myresolver"
      - "traefik.http.services.core.loadbalancer.server.port=8080"
      - "traefik.docker.network=devex_traefik"
    environment:
      SPACES_REGION: "blr1"
      SPACES_BUCKET: "devex"
      SPACES_ENDPOINT: "https://blr1.digitaloceanspaces.com"
      RUNNER_DOCKER_IMAGE: "ghcr.io/parthkapoor-dev/devex/runner-service:latest"
      RUNNER_CLUSTER_IP: "repl.parthkapoor.me"
      KUBE_CONFIG_PATH: "/app/secrets/kubeconfig"
      GITHUB_REDIRECT_URL: "https://api.devx.parthkapoor.me/auth/github/callback"
      FRONTEND_URL: "https://devx.parthkapoor.me"
      ENVIRONMENT: "production"
      PORT: "8080"
    secrets:
      - source: spaces_access_key
        target: SPACES_ACCESS_KEY
      - source: spaces_secret_key
        target: SPACES_SECRET_KEY
      - source: redis_url
        target: REDIS_URL
      - source: github_client_id
        target: GITHUB_CLIENT_ID
      - source: github_client_secret
        target: GITHUB_CLIENT_SECRET
      - source: session_secret
        target: SESSION_SECRET
      - source: kubeconfig_file
        target: /app/secrets/kubeconfig
    networks:
      - traefik
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  traefik-certificates:

secrets:
  spaces_access_key:
    external: true
  spaces_secret_key:
    external: true
  redis_url:
    external: true
  github_client_id:
    external: true
  github_client_secret:
    external: true
  session_secret:
    external: true
  kubeconfig_file:
    external: true
