name: Runner Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "runner/**"
      - ".github/workflows/runner-pipeline.yaml" # Also trigger if the workflow itself changes

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./runner
          push: true
          tags: |
            ghcr.io/parthkapoor-dev/devex/runner-service:latest
            ghcr.io/parthkapoor-dev/devex/runner-service:${{ github.sha }}
