name: Sync Templates to DigitalOcean Spaces

on:
  push:
    paths:
      - "templates/**"
      - "!templates/README.md"
      - "!templates/**/README.md"

jobs:
  sync-templates:
    name: Sync Template Directory
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧮 Calculate template sizes
        id: check_size
        run: |
          echo "Checking template sizes..."
          too_large=false
          max_size_mb=8

          for dir in templates/*; do
            if [ -d "$dir" ]; then
              size=$(du -sm "$dir" | cut -f1)
              echo "Template: $(basename "$dir") Size: ${size}MB"
              if [ "$size" -gt "$max_size_mb" ]; then
                echo "Template $(basename "$dir") exceeds limit."
                too_large=true
              fi
            fi
          done

          echo "too_large=$too_large" >> "$GITHUB_OUTPUT"

      - name: 🚫 Skip if any template is too large
        if: steps.check_size.outputs.too_large == 'true'
        run: |
          echo "One or more templates exceed the max allowed size. Skipping sync."
          exit 0

      - name: ☁️ Sync templates to DigitalOcean Spaces
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
          AWS_DEFAULT_REGION: us-east-1 # Not used but required
        run: |
          aws s3 cp templates/ s3://${{ secrets.DO_SPACES_BUCKET }}/templates/ \
            --recursive \
            --endpoint-url ${{ secrets.DO_SPACES_ENDPOINT }} \
            --exclude "*/README.md"

          echo "✅ Templates synced to DigitalOcean Spaces"
